# Generated by Django 3.1.3 on 2020-11-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloves_small', models.IntegerField()),
                ('gloves', models.IntegerField()),
                ('sweater_small', models.IntegerField()),
                ('sweater', models.IntegerField()),
                ('socks', models.IntegerField()),
                ('muffler', models.IntegerField()),
                ('monkey_cap_small', models.IntegerField()),
                ('monkey_cap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('houseno', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='order',
            name='ordergiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderuser'),
        ),
    ]
