# Generated by Django 3.1.3 on 2020-11-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_order_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('working_cap_perday', models.IntegerField(default=0)),
                ('houseno', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('work_allocated', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='TailorWorkAllocated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloves_small', models.IntegerField()),
                ('gloves', models.IntegerField()),
                ('sweater_small', models.IntegerField()),
                ('sweater', models.IntegerField()),
                ('socks', models.IntegerField()),
                ('muffler', models.IntegerField()),
                ('monkey_cap_small', models.IntegerField()),
                ('monkey_cap', models.IntegerField()),
                ('order_completed', models.BooleanField(default=False)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tailor')),
            ],
        ),
    ]
