# Generated by Django 3.1.3 on 2020-11-07 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tailor_tailorworkallocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorworkallocated',
            name='dateofallocation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
