# Generated by Django 3.1.3 on 2020-11-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tailorworkallocated_dateofallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictwiseReadyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloves_small', models.IntegerField()),
                ('gloves', models.IntegerField()),
                ('sweater_small', models.IntegerField()),
                ('sweater', models.IntegerField()),
                ('socks', models.IntegerField()),
                ('muffler', models.IntegerField()),
                ('monkey_cap_small', models.IntegerField()),
                ('monkey_cap', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
    ]
