# Generated by Django 3.1.3 on 2020-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_districtwisereadylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='gloves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='gloves_small',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='monkey_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='monkey_cap_small',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='muffler',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='socks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='sweater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='districtwisereadylist',
            name='sweater_small',
            field=models.IntegerField(default=0),
        ),
    ]
