# Generated by Django 3.1.3 on 2020-11-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201107_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorworkallocated',
            name='picked_up_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Valet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('vehicleno', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
    ]
